package com.lukasowy.controllers.rest;

import java.util.Collection;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import com.lukasowy.models.Book;
import com.lukasowy.services.DaoService;

@RestController// This means that this class is a Controller
public class MainRestController {

	@Autowired	// This means to get the bean called daoService
    // Which is auto-generated by Spring, we will use it to handle the data
	private DaoService daoService;
	
	@GetMapping("/")
	public Collection<Book> getAllBooks(){
		// This returns a JSON  with the books
		return daoService.findAllBooks();
	}
	
}
